/**
 * \file IfxCbs_PinMap_TC33xED_LFBGA180_adas.h
 * \brief CBS I/O map
 * \ingroup IfxLld_Cbs
 *
 * \version iLLD_1_21_0
 * \copyright Copyright (c) 2024 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * \defgroup IfxLld_Cbs_pinmap CBS Pin Mapping
 * \ingroup IfxLld_Cbs
 */

#ifndef IFXCBS_PINMAP_TC33XED_LFBGA180_ADAS_H
#define IFXCBS_PINMAP_TC33XED_LFBGA180_ADAS_H  1

#include <IfxCbs_reg.h>
#include <Port/Std/IfxPort.h>
#include "Ifx_PinMap.h"

/** \addtogroup IfxLld_Cbs_pinmap
 * \{ */

typedef enum
{
    IfxCbs_TriggerPin_0 = 0,
    IfxCbs_TriggerPin_1 = 1,
    IfxCbs_TriggerPin_2 = 2,
    IfxCbs_TriggerPin_3 = 3,
    IfxCbs_TriggerPin_4 = 4,
    IfxCbs_TriggerPin_5 = 5,
    IfxCbs_TriggerPin_6 = 6,
    IfxCbs_TriggerPin_7 = 7      
} IfxCbs_TriggerPin; 

/** \brief CBS TGI pin mapping structure */
typedef const struct
{
    Ifx_CBS*         module;    /**< \brief Base address */
    IfxCbs_TriggerPin pinId; /**< \brief Channel ID */
    IfxPort_Pin       pin;       /**< \brief Port pin */
    Ifx_RxSel         select;    /**< \brief Input multiplexer value */
} IfxCbs_Tgi_In;

/** \brief CBS TGO pin mapping structure */
typedef const struct
{
    Ifx_CBS*         module;    /**< \brief Base address */
    IfxCbs_TriggerPin pinId; /**< \brief Channel ID */
    IfxPort_Pin       pin;       /**< \brief Port pin */
    IfxPort_OutputIdx select;    /**< \brief Port control code */
} IfxCbs_Tgo_Out;

IFX_EXTERN IfxCbs_Tgi_In IfxCbs_TGI0_P20_0_IN;  /**< \brief Trigger input */
IFX_EXTERN IfxCbs_Tgi_In IfxCbs_TGI2_P21_6_IN;  /**< \brief Trigger input */
IFX_EXTERN IfxCbs_Tgi_In IfxCbs_TGI3_P21_7_IN;  /**< \brief Trigger input */
IFX_EXTERN IfxCbs_Tgo_Out IfxCbs_TGO0_P20_0_OUT;  /**< \brief Trigger output */
IFX_EXTERN IfxCbs_Tgo_Out IfxCbs_TGO2_P21_6_OUT;  /**< \brief Trigger output */
IFX_EXTERN IfxCbs_Tgo_Out IfxCbs_TGO3_P21_7_OUT;  /**< \brief Trigger output */

/** \brief Table dimensions */
#define IFXCBS_PINMAP_NUM_MODULES 1
#define IFXCBS_PINMAP_NUM_CHANNELS 4
#define IFXCBS_PINMAP_TGI_IN_NUM_ITEMS 1
#define IFXCBS_PINMAP_TGO_OUT_NUM_ITEMS 1


/** \brief IfxCbs_Tgi_In table */
IFX_EXTERN const IfxCbs_Tgi_In *IfxCbs_Tgi_In_pinTable[IFXCBS_PINMAP_NUM_MODULES][IFXCBS_PINMAP_NUM_CHANNELS][IFXCBS_PINMAP_TGI_IN_NUM_ITEMS];

/** \brief IfxCbs_Tgo_Out table */
IFX_EXTERN const IfxCbs_Tgo_Out *IfxCbs_Tgo_Out_pinTable[IFXCBS_PINMAP_NUM_MODULES][IFXCBS_PINMAP_NUM_CHANNELS][IFXCBS_PINMAP_TGO_OUT_NUM_ITEMS];

/** \} */

#endif /* IFXCBS_PINMAP_TC33XED_LFBGA180_ADAS_H */
