/**
 * \file IfxCbs_PinMap_TC33xED_LFBGA180_adas.c
 * \brief CBS I/O map
 * \ingroup IfxLld_Cbs
 *
 * \version iLLD_1_21_0
 * \copyright Copyright (c) 2024 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "Ifx_Cfg.h"
#if defined (__TASKING__)
#pragma warning 508		    /* To suppress empty file warning */
#endif
#if defined (__ghs__)
#pragma diag_suppress 96	/* To suppress empty file warning */
#endif
#if defined DEVICE_TC33XED && defined IFX_PIN_PACKAGE_LFBGA180_ADAS
#include "IfxCbs_PinMap_TC33xED_LFBGA180_adas.h"

IfxCbs_Tgi_In IfxCbs_TGI0_P20_0_IN = {&MODULE_CBS, IfxCbs_TriggerPin_0, {&MODULE_P20, 0}, Ifx_RxSel_a};
IfxCbs_Tgi_In IfxCbs_TGI2_P21_6_IN = {&MODULE_CBS, IfxCbs_TriggerPin_2, {&MODULE_P21, 6}, Ifx_RxSel_a};
IfxCbs_Tgi_In IfxCbs_TGI3_P21_7_IN = {&MODULE_CBS, IfxCbs_TriggerPin_3, {&MODULE_P21, 7}, Ifx_RxSel_a};
IfxCbs_Tgo_Out IfxCbs_TGO0_P20_0_OUT = {&MODULE_CBS, IfxCbs_TriggerPin_0, {&MODULE_P20, 0}, IfxPort_OutputIdx_general};
IfxCbs_Tgo_Out IfxCbs_TGO2_P21_6_OUT = {&MODULE_CBS, IfxCbs_TriggerPin_2, {&MODULE_P21, 6}, IfxPort_OutputIdx_general};
IfxCbs_Tgo_Out IfxCbs_TGO3_P21_7_OUT = {&MODULE_CBS, IfxCbs_TriggerPin_3, {&MODULE_P21, 7}, IfxPort_OutputIdx_general};


const IfxCbs_Tgi_In *IfxCbs_Tgi_In_pinTable[IFXCBS_PINMAP_NUM_MODULES][IFXCBS_PINMAP_NUM_CHANNELS][IFXCBS_PINMAP_TGI_IN_NUM_ITEMS] = {
    {
        {
            &IfxCbs_TGI0_P20_0_IN
        },
        {
            NULL_PTR
        },
        {
            &IfxCbs_TGI2_P21_6_IN
        },
        {
            &IfxCbs_TGI3_P21_7_IN
        }
    }
};

const IfxCbs_Tgo_Out *IfxCbs_Tgo_Out_pinTable[IFXCBS_PINMAP_NUM_MODULES][IFXCBS_PINMAP_NUM_CHANNELS][IFXCBS_PINMAP_TGO_OUT_NUM_ITEMS] = {
    {
        {
            &IfxCbs_TGO0_P20_0_OUT
        },
        {
            NULL_PTR
        },
        {
            &IfxCbs_TGO2_P21_6_OUT
        },
        {
            &IfxCbs_TGO3_P21_7_OUT
        }
    }
};
#endif
#if defined (_TASKING_) || defined (_ghs_)
#pragma restore
#endif
